services:
  terraform:
    build: .
    container_name: terraform
    volumes:
      - ./build/terraform/${STAGE}:/terraform
      - ~/.aws:/root/.aws:ro
    working_dir: /terraform
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_PROFILE